### ISSUE TITLE
Allow 'name' attribute to be provided for input field

### ISSUE THREAD

**Issue by georgewhewell** [angular-cron-jobs/angular-cron-jobs#20]
I'm using this directive as a enhancement for an text input field in a server-side generated form. Currently I'm binding the output to my own hidden field so that the form can be submitted via POST, but it would be nice if this could be integrated into the directive.
E,g If the element the directive is applied to has a 'name' attribute, copy it to the inner select input

I may attempt a pull request for this if other may find it useful.

**Comment by jacobscarter** [comment]
@georgewhewell do you still want to make a PR for this?

**Comment by georgewhewell** [comment]
@jacobscarter didn't get around to this. have moved on to other things so won't be able to, sorry.
