### ISSUE TITLE
supports events

### ISSUE THREAD

**Issue by iveretelnyk** [angular-cron-jobs/angular-cron-jobs#51]
It is not possible to know if value beet changed. I used $watch, but it does not same as blur or change.

**Comment by jacobscarter** [comment]
I'm not sure I understand your question, whatever you have bound to ngModel on the directive will change when the value changes, if you watch that ngModel value you can detect changes.

**Comment by iveretelnyk** [comment]
$watch() and ng-change is different and used for different puposes, not counting using $watch is not recommended. It would be great to have ng-change event supported

**Comment by RajanRastogi** [comment]
`ng-change` event should be triggered. Works for me.

**Comment by jacobscarter** [comment]
@iveretelnyk can you provide a Fiddle of this error occurring?

**Comment by iveretelnyk** [comment]
Sorry, used old version, updated and ng-change works. Thank you in advance.

**Comment by RajanRastogi** [comment]
I think we can close this.
