### ISSUE TITLE
Incorrect count of days in month

### ISSUE THREAD

**Issue by alexand34** [angular-cron-jobs/angular-cron-jobs#67]
[https://www.dropbox.com/s/8dvdopg2fxqphcw/Untitled.png?dl=0](url)

**Comment by jacobscarter** [comment]
bad link, you can add images to github comments as file uploads

**Comment by alexand34** [comment]
![untitled](https://user-images.githubusercontent.com/10760805/29480657-c2030080-842e-11e7-8ae4-0a775dc6b2b7.png)
